# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-09 19:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_mock_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mock_client',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
    ]
