# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-10 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170410_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mock_client',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team_members',
            field=models.ManyToManyField(blank=True, default=b'', null=True, to='accounts.IronMan'),
        ),
    ]
