# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-10 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170410_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='team_members',
            field=models.ManyToManyField(blank=True, default=b'', to='accounts.IronMan'),
        ),
    ]
