# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_evaluate'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluate',
            name='feedback',
            field=models.TextField(default=b''),
        ),
    ]
