# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_evaluate_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='mentor',
            field=models.CharField(default=b'', max_length=40),
        ),
    ]
