# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170411_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='prod',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='team',
        ),
        migrations.DeleteModel(
            name='Bug',
        ),
    ]
