# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20170411_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='vertical',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
