# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 18:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_folder_vertical'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluate',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 17, 18, 14, 24, 699022)),
        ),
        migrations.AddField(
            model_name='folder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 17, 18, 14, 24, 698339)),
        ),
        migrations.AddField(
            model_name='ironman',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 17, 18, 14, 24, 695950)),
        ),
        migrations.AlterField(
            model_name='evaluate',
            name='feedback',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='folder',
            name='mentor',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='ironman',
            name='mid_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='team_members',
            field=models.ManyToManyField(blank=True, default='', to='accounts.IronMan'),
        ),
    ]
