# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 18:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20170417_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluate',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='folder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='ironman',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
