# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_folder_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
