# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 08:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0014_auto_20170411_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.TextField(default='', verbose_name='Enter Bug/Request')),
                ('que', models.BooleanField(default=True, verbose_name='Bug?')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Product')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scrum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_yest', models.TextField(max_length=500)),
                ('roadblk', models.CharField(blank=True, max_length=500)),
                ('plan_tdy', models.CharField(max_length=500)),
                ('learning', models.CharField(blank=True, max_length=500)),
                ('date', models.DateField(default='2011-11-11')),
                ('created_by', models.CharField(max_length=50)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Project')),
            ],
        ),
        migrations.CreateModel(
            name='SessionReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SessionOn', models.CharField(max_length=30)),
                ('Details', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(default='2011-11-11')),
                ('votes', models.IntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Project')),
            ],
        ),
        migrations.CreateModel(
            name='synthesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=1000)),
                ('source', models.URLField()),
                ('by', models.CharField(max_length=15)),
            ],
        ),
    ]
