# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 10:47
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_folder_vertical'),
        ('ironman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', verbose_name='Write what you want to share')),
                ('time', models.DateTimeField(default=datetime.datetime(2017, 4, 11, 16, 17, 36, 753000))),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Project')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
