# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-21 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ironman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrum',
            name='roadblk',
            field=models.CharField(blank=True, max_length=500, verbose_name='RoadBlocks if any'),
        ),
        migrations.RemoveField(
            model_name='sessionreq',
            name='votes',
        ),
        migrations.AddField(
            model_name='sessionreq',
            name='votes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
