# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-05 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrum',
            name='date',
            field=models.DateField(default=1989),
        ),
    ]
