# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 18:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironman', '0002_sharedoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 17, 18, 14, 24, 701743)),
        ),
        migrations.AddField(
            model_name='synthesis',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 17, 18, 14, 24, 701248)),
        ),
        migrations.AlterField(
            model_name='sharedoc',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 17, 18, 14, 24, 702300)),
        ),
    ]
