# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-05 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironman', '0002_auto_20170405_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrum',
            old_name='by',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='scrum',
            name='date',
            field=models.DateField(default='2011-11-11'),
        ),
    ]
