# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-06 04:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironman', '0003_auto_20170405_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='sess_req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SessionOn', models.CharField(max_length=30)),
                ('Details', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(default=datetime.date(2017, 4, 6))),
            ],
        ),
    ]
