# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 18:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironman', '0003_auto_20170417_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='sharedoc',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='synthesis',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
