# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-06 04:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ironman', '0004_sess_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sess_req',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 6, 4, 59, 19, 116000, tzinfo=utc)),
        ),
    ]
