# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-06 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ironman', '0005_auto_20170406_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SessionOn', models.CharField(max_length=30)),
                ('Details', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='sess_req',
        ),
    ]
