# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-06 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironman', '0006_auto_20170406_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionreq',
            name='project',
            field=models.CharField(default='mumix', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scrum',
            name='comp_yest',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sessionreq',
            name='date',
            field=models.DateField(default='2011-11-11'),
        ),
    ]
