# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-06 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironman', '0007_auto_20170406_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='synthesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=1000)),
                ('source', models.URLField()),
                ('by', models.CharField(max_length=15)),
            ],
        ),
    ]
