# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-10 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ironman', '0009_scrum_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionreq',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Project'),
        ),
    ]
