# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-10 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironman', '0010_auto_20170410_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionreq',
            name='votes',
            field=models.IntegerField(default=1),
        ),
    ]
